
try:
    test(123)
except Exception as e:
    logging.exception("Exception occurred")

